### ISSUE TITLE
[native_storage] Lower Android API level 23 to 21

### ISSUE THREAD

**Issue by rubenferreira97** [celest-dev/celest#121]
It would be possible to lower the minSdkVersion to 21?
I gave a quick look to the source code and I couldn't find any incompatibility issues since: 

> **Version 1.1.0-alpha01**
> Lollipop (API Level 21+) is now supported. Please note that the AndroidKeyStore is not used for API 21 and 22. ([I7c12d](https://android-review.googlesource.com/#/q/I7c12d205273e4b652271865e53ff6c406632f407), [b/132325342](https://issuetracker.google.com/issues/132325342))

However, don't know if this have some implications:
> developers should be aware that the keystore will _not_ be used on Android L (API 21 and 22)

**Comment by dnys1** [comment]
Fixed in 0.1.4 :-)

Good catch!
