### ISSUE TITLE
Can't run `celest uninstall`

### ISSUE THREAD

**Issue by rubenferreira97** [celest-dev/celest#13]
Hi guys, trying out `celest` on Windows!

I am hitting a crash when running `celest uninstall`. 
It seems there is a dart version mismatch happening due some caching (don't know if this is only a visual glitch):

![image](https://github.com/celest-dev/celest/assets/43851289/b63dac4e-1aaf-4195-b43f-fb7c3f4bd317)

This happened due a switch between `beta -> stable` flutter version.
I was trying to reinstall celest to try to fix this mismatch.
Installing again does not solve the issue.

**Comment by abdallahshaban557** [comment]
We saw the issue come through. We have a fix coming out for it shortly! Thank you for letting us know!

**Comment by rubenferreira97** [comment]
@abdallahshaban557  Wow, thanks for the quick feedback!

I found another issue (I think it might be a funny bug), don't know if is already tracked. If we create a project named `celest` with `flutter create celest` running `celest start` inside the project crashes. 

<img alt="image" src="https://github.com/celest-dev/celest/assets/43851289/eb1dc672-610c-46ad-b406-398b37e175fa">

Don't know if I should create a new issue.

**Comment by abdallahshaban557** [comment]
We fixed this as well - we'll get this release out in a bit! No need for a new issue, but thanks for checking!

**Comment by dnys1** [comment]
Both issues have been fixed now. Thanks for bringing them to our attention!

You can head over to https://celest.dev/download to get the latest version. We've also added a new `celest upgrade` command so that in the future, you'll just be able to run that.

Thanks again! 🚀
