### ISSUE TITLE
New Feature Request: Supabase package support. 

### ISSUE THREAD

**Issue by ps6067966** [celest-dev/celest#151]
There is dart-only version of supabase package. but currently not working with celest. 
I'm already using supabase and dart frog in some projects. 

Please add supabase support.

**Comment by ps6067966** [comment]
@dnys1

**Comment by dnys1** [comment]
Hey Pratap, sorry for the delay. Looking into this now 👍

**Comment by dnys1** [comment]
Hi @ps6067966, we've identified the issue and are working on a permanent fix. In the meantime, if you add the following to your `celest/pubspec.yaml`, you should be able to continue working:

```yaml
dependency_overrides:
  web_socket_channel: ^3.0.0
```

Apologies for the inconvenience. I'll leave this issue open until it is fully resolved.

**Comment by dnys1** [comment]
Hi @ps6067966, the fix for this has been released in CLI version 0.4.7. Please run `celest upgrade` and let me know if you face any more issues!
