### ISSUE TITLE
Server is very slow. is there any way to fix this?

### ISSUE THREAD

**Issue by ps6067966** [celest-dev/celest#155]

**Comment by dnys1** [comment]
Hi @ps6067966 sorry you are facing issues. Do you mean it is slow to deploy projects or that once they are deployed, you are noticing high latencies?

**Comment by ps6067966** [comment]
> Hi @ps6067966 sorry you are facing issues. Do you mean it is slow to deploy projects or that once they are deployed, you are noticing high latencies?

Both. slow to deploy and latency as well.

**Comment by ps6067966** [comment]
![image](https://github.com/celest-dev/celest/assets/26248740/ea07988f-09e2-4fb6-b004-78dbe8fd465b)


also this error message.

**Comment by ps6067966** [comment]
Any paid version or subscription.

**Comment by ps6067966** [comment]
@dnys1

**Comment by dnys1** [comment]
Hey @ps6067966, can we hop on a call at your convenience? I'd love to better understand what we can be doing better.

https://cal.com/celest-dev/dillon

**Comment by ps6067966** [comment]
> Hey @ps6067966, can we hop on a call at your convenience? I'd love to better understand what we can be doing better.
> 
> https://cal.com/celest-dev/dillon

Sorry I couldn't connect last time. 

Can we connect today?

**Comment by dnys1** [comment]
@ps6067966 no worries. Yes, please feel free to find another time that works for you.

**Comment by ps6067966** [comment]
@dnys1 

Server is very very slow in india. Please check and do something about it.

**Comment by dnys1** [comment]
Let me know if you still experience this in Celest v1!
