### ISSUE TITLE
What is future planning for this project? is any new features coming?

### ISSUE THREAD

**Issue by ps6067966** [celest-dev/celest#159]

**Comment by dnys1** [comment]
Hi Pratap 👋 

I apologize for the lack of communication around Celest. The project is still very much alive and we are planning to have some big news within the next month or two 🙂

Lots of new features and a better platform are coming. Stay tuned! 🙌

**Comment by ps6067966** [comment]
> Hi Pratap 👋 
> 
> I apologize for the lack of communication around Celest. The project is still very much alive and we are planning to have some big news within the next month or two 🙂
> 
> Lots of new features and a better platform are coming. Stay tuned! 🙌

I'm super excited for this project.

**Comment by dnys1** [comment]
Us too. Thank you so much for your support! 😄

**Comment by dnys1** [comment]
I'm thrilled to share the release of Celest v1! https://github.com/celest-dev/celest/releases/tag/v1.0.0

We are just getting started with this launch and we we believe it gives us a foundation that we can iterate on more quickly going forward 😎 

Let us know what you think!
