### ISSUE TITLE
Installation process on Linux OS

### ISSUE THREAD

**Issue by blaqshyd** [celest-dev/celest#16]
The celest file gotten after unzipping the zip file is not executable even after making it executable . It would be nice to include some kind of guide for installing on Linux because I reproduced the installation process on Windows and it was seamless but I had to manually set it up on Linux thanks to GPT.

**Comment by abdallahshaban557** [comment]
Hi @blaqshyd - thank you for this feedback - we will look into it and get back to you ASAP.

**Comment by blaqshyd** [comment]
@dnys1 Yes, it does but I had issues with it still because of the libdart_sqlite3.so. Here is how I was able to install it:

- Check Your System Architecture
`uname -m`
- Download and unzip manually or in the terminal and navigate to the desired location
`unzip celest-latest-linux_x64zip`

- Make it executable 
`chmod +x celest`

- Ensure that the directory containing "libdart_sqlite3.so" is in the system's library search path.

```
export PATH="/path/to/celest:$PATH"
export LD_LIBRARY_PATH=/path/to/celestlib:$LD_LIBRARY_PATH
```

**Comment by abdallahshaban557** [comment]
Hi @blaqshyd - we are looking into it as well. Thank you for this feedback!

**Comment by blaqshyd** [comment]
@abdallahshaban557 Thank you for your response. It's okay to close the issue or leave it open?

**Comment by abdallahshaban557** [comment]
Let us keep it open for now! Thank you for checking.

**Comment by dnys1** [comment]
Hi @blaqshyd, we've created some DEB installers now which should make the installation much smoother on Linux. I've updated the [download](https://celest.dev/download) page with links. Give them a try if you'd like!

Closing this for now, but please let us know if you experience any more issues. Thanks for the ticket!

**Comment by blaqshyd** [comment]
@dnys1 The deb installer was so much easier to setup. Awesome work and looking forward to more things to be done with celest 🚀

**Comment by dnys1** [comment]
@blaqshyd I'm so glad to hear that! 🎉
