### ISSUE TITLE
Bug when starting Celest

### ISSUE THREAD

**Issue by marcglasberg** [celest-dev/celest#53]
There are no errors in the project. But it says there are, and then printed another line saying `Starting Celest`. The number of seconds in this second line keep growing and it never stops.

```
PS C:\Users\Marcelo\MobileAppFlutterCelest> celest start
⠴ Starting Celest... (4.5s)Project has errors. Please fix them and save the corresponding files.
⠇ Starting Celest... (118.3s)
```

Note: I'm trying to run it with `celest.init(environment: CelestEnvironment.local);`

If I stop and try again, the same happens.

**Comment by dnys1** [comment]
Hmm, I think I see the error in Sentry. Can you share the code for the `Portfolio` class?

**Comment by dnys1** [comment]
Just pushed a release with the fix! 🚀 

Please let me know if you run into any more issues.
