### ISSUE TITLE
Improve/Update the docs

### ISSUE THREAD

**Issue by marcglasberg** [celest-dev/celest#54]
# https://celest.dev/docs/functions/data-types 

* What's really the requirement for automatic serialization here? Do you need to make sure one of the constructors have the name of the parameters equal to the name of the fields? And the types of this constructor parameters must be compatible with the serialized JSON?

* When you say `Celest does not support the following Dart types as parameter or return types. ` you are referring to the **Celest functions**. However, you can't also have Stream/Object/dynamic
as fields your custom types, and you can't have them in the constructor that's going to be used for the serialization. The docs don't explain that.

* Instead of `To have Celest use that custom class, you need to place it in the <flutter_app>/celest/lib/models/ folder.` should you say you must export them from there, and you can put them anywhere?

---

# https://celest.dev/docs/functions/exceptions

* Should explain how to use exceptions from third-party packages.

* Instead of `You can create exceptions inside your celest/lib/exceptions/ folder.` 
should you say you must export them from there, and you can put them anywhere?

---

# Start/Deploy

* Add `celest deploy` to https://celest.dev/docs/cli-commands-reference

* Explain: 
    ```dart
    celest.init(environment: CelestEnvironment.local);
    celest.init(environment: CelestEnvironment.production);
    ```

**Comment by dnys1** [comment]
Thanks, @marcglasberg! All these updates have been made :-)
