### ISSUE TITLE
about celest cloud environment

### ISSUE THREAD

**Issue by starklord** [celest-dev/celest#93]
Hi i could successfully run celest deploy and now i want to create a database layer in the celest cloud and with that i can create a complete application. 
For that i dont know if there are support for databases inside the celest cloud. Also if there is permissons to write files.
Or maybe these things are out of the celest cloud scope?

**Comment by dnys1** [comment]
Hey @starklord!

Currently, Celest does not offer its own database solution, but it's the next item on the roadmap, along with connectors to existing Postgres databases. In the meantime, I would recommend a serverless database offering like Turso, Neon, or Planetscale for your data.

**Comment by dnys1** [comment]
I'll close this for now, but happy to help further if you run into any issues.

Check out the [environment variables](https://celest.dev/docs/functions/env-variables) guide for securely injecting API keys into your backend for accessing these services.
